renderSidebar('Players');
attachSearchDropdown(document.getElementById('searchBox'));

const params = new URLSearchParams(location.search);
const NAME = params.get('name');
const SEASON = params.get('season');

// minimal Markdown -> HTML for the report (headings, bold/italic, bullet lists, paragraphs)
function mdToHtml(md) {
  const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const inline = (s) => esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*(?!\s)(.+?)\*/g, '$1<em>$2</em>');
  let html = '', inList = false;
  const closeList = () => { if (inList) { html += '</ul>'; inList = false; } };
  for (const raw of md.split('\n')) {
    const line = raw.replace(/\s+$/, '');
    if (/^### /.test(line)) { closeList(); html += '<h3>' + inline(line.slice(4)) + '</h3>'; }
    else if (/^## /.test(line)) { closeList(); html += '<h2>' + inline(line.slice(3)) + '</h2>'; }
    else if (/^# /.test(line)) { closeList(); html += '<h1>' + inline(line.slice(2)) + '</h1>'; }
    else if (/^\s*[-*] /.test(line)) { if (!inList) { html += '<ul>'; inList = true; } html += '<li>' + inline(line.replace(/^\s*[-*] /, '')) + '</li>'; }
    else if (line.trim() === '') { closeList(); }
    else { closeList(); html += '<p>' + inline(line) + '</p>'; }
  }
  closeList();
  return html;
}

const body = () => document.getElementById('sr-body');

function renderError(msg) {
  document.getElementById('regen').style.display = 'none';
  body().innerHTML = `<div class="sr-empty">
    <div class="sr-empty-ic">📋</div>
    <p>${msg.replace(/</g, '&lt;')}</p>
    ${NAME ? `<a class="btn btn-ghost" href="/player.html?name=${encodeURIComponent(NAME)}">← Back to ${NAME}'s profile</a>` : ''}
  </div>`;
}

let POLL_TOKEN = 0;   // invalidates in-flight polls when the user regenerates

function render(d, pending) {
  const when = d.generated_at ? new Date(d.generated_at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '';
  const badge = pending
    ? `<span class="sr-ai-chip"><span class="sr-spinner sr-spinner-sm"></span>Polishing the full AI report…</span>`
    : `<span>Generated by ${d.model || 'Claude'}${d.cached ? ' · cached' : ''}${when ? ' · ' + when : ''}</span>`;
  body().innerHTML = `
    <div class="sr-paper">${mdToHtml(d.report)}</div>
    <div class="sr-meta">
      ${badge}
      <a href="/player.html?name=${encodeURIComponent(NAME)}">View full profile →</a>
    </div>`;
  const btn = document.getElementById('regen');
  btn.style.display = pending ? 'none' : '';
  btn.onclick = () => load(true);
}

// Poll (without refresh) until the background AI report lands in the cache, then swap
// it in. Gives up quietly after ~60s, leaving the instant report on screen.
async function pollForAi(token, tries) {
  if (token !== POLL_TOKEN || tries <= 0) return;
  await new Promise((r) => setTimeout(r, 4000));
  if (token !== POLL_TOKEN) return;
  let qs = '/api/scout_report?name=' + encodeURIComponent(NAME);
  if (SEASON) qs += '&season=' + encodeURIComponent(SEASON);
  let d;
  try { d = await api(qs); } catch { pollForAi(token, tries - 1); return; }
  if (token !== POLL_TOKEN) return;
  if (d.available && d.cached) { render(d, false); return; }   // AI report ready
  pollForAi(token, tries - 1);
}

async function load(refresh) {
  if (!NAME) { renderError('No player selected. Open a player profile and click “Scout Report”.'); return; }
  document.getElementById('crumb').textContent = NAME;
  document.getElementById('regen').style.display = 'none';
  const token = ++POLL_TOKEN;
  body().innerHTML = `<div class="sr-empty"><div class="sr-spinner"></div>
    <p>Scouting <b>${NAME}</b>…</p></div>`;
  let qs = '/api/scout_report?name=' + encodeURIComponent(NAME);
  if (SEASON) qs += '&season=' + encodeURIComponent(SEASON);
  if (refresh) qs += '&refresh=1';
  let d;
  try { d = await api(qs); } catch { renderError('Could not reach the report service.'); return; }
  if (token !== POLL_TOKEN) return;
  if (!d.available) { renderError(d.error || 'Report unavailable.'); return; }

  render(d, !!d.pending);
  if (d.pending) pollForAi(token, 15);   // upgrade to the AI report when it's ready
}

load(false);
