renderSidebar('Players');
attachSearchDropdown(document.getElementById('searchBox'));

const params = new URLSearchParams(location.search);
const NAME = params.get('name');
const SEASON = params.get('season');

// minimal Markdown -> HTML for the report (headings, bold/italic, bullet lists, paragraphs)
function mdToHtml(md) {
  const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const inline = (s) => esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[^*])\*(?!\s)(.+?)\*/g, '$1<em>$2</em>');
  let html = '', inList = false;
  const closeList = () => { if (inList) { html += '</ul>'; inList = false; } };
  for (const raw of md.split('\n')) {
    const line = raw.replace(/\s+$/, '');
    if (/^### /.test(line)) { closeList(); html += '<h3>' + inline(line.slice(4)) + '</h3>'; }
    else if (/^## /.test(line)) { closeList(); html += '<h2>' + inline(line.slice(3)) + '</h2>'; }
    else if (/^# /.test(line)) { closeList(); html += '<h1>' + inline(line.slice(2)) + '</h1>'; }
    else if (/^\s*[-*] /.test(line)) { if (!inList) { html += '<ul>'; inList = true; } html += '<li>' + inline(line.replace(/^\s*[-*] /, '')) + '</li>'; }
    else if (line.trim() === '') { closeList(); }
    else { closeList(); html += '<p>' + inline(line) + '</p>'; }
  }
  closeList();
  return html;
}

const body = () => document.getElementById('sr-body');

function renderError(msg) {
  document.getElementById('regen').style.display = 'none';
  body().innerHTML = `<div class="sr-empty">
    <div class="sr-empty-ic">📋</div>
    <p>${msg.replace(/</g, '&lt;')}</p>
    ${NAME ? `<a class="btn btn-ghost" href="/player.html?name=${encodeURIComponent(NAME)}">← Back to ${NAME}'s profile</a>` : ''}
  </div>`;
}

async function load(refresh) {
  if (!NAME) { renderError('No player selected. Open a player profile and click “Scout Report”.'); return; }
  document.getElementById('crumb').textContent = NAME;
  document.getElementById('regen').style.display = 'none';
  body().innerHTML = `<div class="sr-empty"><div class="sr-spinner"></div>
    <p>Scouting <b>${NAME}</b>… the report is being written from the data. This can take ~20–40 seconds.</p></div>`;
  let qs = '/api/scout_report?name=' + encodeURIComponent(NAME);
  if (SEASON) qs += '&season=' + encodeURIComponent(SEASON);
  if (refresh) qs += '&refresh=1';
  let d;
  try { d = await api(qs); } catch { renderError('Could not reach the report service.'); return; }
  if (!d.available) { renderError(d.error || 'Report unavailable.'); return; }

  const when = d.generated_at ? new Date(d.generated_at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '';
  body().innerHTML = `
    <div class="sr-paper">${mdToHtml(d.report)}</div>
    <div class="sr-meta">
      <span>Generated by ${d.model || 'Claude'}${d.cached ? ' · cached' : ''}${when ? ' · ' + when : ''}</span>
      <a href="/player.html?name=${encodeURIComponent(NAME)}">View full profile →</a>
    </div>`;
  const btn = document.getElementById('regen');
  btn.style.display = '';
  btn.onclick = () => load(true);
}

load(false);
